const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
 const page=await browser.newPage({viewport:{width:1512,height:1060},deviceScaleFactor:1});
 const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:3000')&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))external.push(r.url());});
 const output=path.resolve(__dirname,'../docs/screenshots');fs.mkdirSync(output,{recursive:true});
 await page.goto('http://127.0.0.1:3000/#clients');await page.locator('#client-list tbody tr').first().waitFor();
 assert.equal(await page.locator('#client-list tbody tr').count(),50);
 assert.equal(await page.locator('#graph,#flow-card').count(),0);
 await page.selectOption('#page-size','100000');assert.equal(await page.locator('#client-list tbody tr').count(),2248);
 await page.selectOption('#client-role','coordinator');assert.equal(await page.locator('#client-list tbody tr').count(),38);
 const gid=await page.locator('#client-list tbody tr').first().getAttribute('data-gid');assert.match(gid,/^\d{18}$/);
 await page.fill('#client-search',gid);assert.equal(await page.locator('#client-list tbody tr').count(),1);
 await page.fill('#client-search','');await page.selectOption('#client-role','');await page.selectOption('#page-size','50');
 await page.selectOption('#client-sort','ascending');assert.equal((await page.locator('.score strong').first().textContent()).replace(',','.'),'0.000');
 await page.selectOption('#client-sort','descending');await page.screenshot({path:path.join(output,'clients-dark.png')});
 await page.click('#theme');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.screenshot({path:path.join(output,'clients-light.png')});
 for(const [lang,title] of [['en','Client review'],['kk','Клиенттерді тексеру'],['ru','Проверка клиентов']]){await page.selectOption('#language',lang);assert.equal(await page.locator('#title').textContent(),title);}
 await page.click('[data-section="clusters"]');await page.locator('.cluster-card').first().waitFor();assert.equal(await page.locator('.cluster-card').first().locator('tbody tr').count(),6);
 assert.match(await page.locator('.cluster-card thead').first().textContent(),/OR.*95% ДИ.*q-value/);
 await page.check('#signals-only');assert.ok(await page.locator('.signal.flagged').count()>0);await page.screenshot({path:path.join(output,'signals-light.png')});
 await page.click('[data-section="method"]');await page.locator('.method-hero').waitFor();assert.equal(await page.locator('details[open]').count(),0);await page.locator('summary').nth(1).click();assert.equal(await page.locator('details[open]').count(),1);
 await page.screenshot({path:path.join(output,'method-light.png')});
 await page.click('[data-section="flow"]');await page.locator('#graph canvas').first().waitFor();await page.fill('#flow-search',gid);await page.getByRole('button',{name:'Найти',exact:true}).click();assert.match(await page.locator('#flow-card').textContent(),new RegExp(gid));
 await page.screenshot({path:path.join(output,'flow-light.png')});
 const data=await (await page.request.get('http://127.0.0.1:3000/api/dataset')).json();
 assert.equal(Math.min(...data.clusters.map(c=>c.cluster_id)),1);
 assert.match(await page.locator('#stats').textContent(),/На границе наблюдения444/);
 assert.equal(await page.locator('.mini-columns').getAttribute('style'),'--columns: 3;');
 assert.equal(await page.locator('.node-metrics>div').count(),10);
 assert.match(await page.locator('#flow-card').textContent(),/Сопоставимо за 1–2 дня/);
 const probe=async n=>{await page.fill('#flow-search',n.gid);await page.getByRole('button',{name:'Найти',exact:true}).click();};
 await probe(data.graph.nodes.find(n=>n.in_deg>0&&n.out_deg===0));
 assert.equal(await page.locator('.mini-columns').getAttribute('style'),'--columns: 2;');
 await probe(data.graph.nodes.find(n=>n.in_deg===0&&n.out_deg>0));
 assert.equal(await page.locator('.mini-columns').getAttribute('style'),'--columns: 2;');
 await probe(data.graph.nodes.find(n=>n.in_deg===0&&n.out_deg===0));
 assert.equal(await page.locator('.mini-columns').getAttribute('style'),'--columns: 1;');
 assert.match(await page.locator('#flow-card').textContent(),/Операций в выборке нет/);
 await probe(data.graph.nodes.find(n=>n.is_seed&&n.in_deg>0&&n.out_deg>0));
 assert.match(await page.locator('.node-metrics').textContent(),/Не используется/);
 await page.locator('#flow-card summary').filter({hasText:'Правило и вклад'}).click();
 assert.equal(await page.locator('.contributions>div').count(),3);
 await page.screenshot({path:path.join(output,'flow-seed-details.png')});
 for(const [lang,label] of [['en','Seed ancestors'],['kk','Seed бастаулары'],['ru','Seed-предков']]){await page.selectOption('#language',lang);assert.ok((await page.locator('#flow-card').textContent()).includes(label));}
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('#flow-mini').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'flow-mobile.png')});
 await page.setViewportSize({width:1512,height:1060});
 await page.click('[data-section="clients"]');
 await page.locator('#files').setInputFiles([{name:'wrong.parquet',mimeType:'application/octet-stream',buffer:Buffer.from('bad')}]);await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Нужны ровно'));
 await page.locator('#files').setInputFiles(['nodes.parquet','edges.parquet','transactions.parquet'].map(name=>path.resolve(__dirname,'../data/raw',name)));
 await page.waitForFunction(()=>document.querySelector('#source').textContent.includes('Ваш набор'),{},{timeout:300000});
 assert.match(await page.locator('#notice').textContent(),/памяти/);assert.equal(await page.locator('#graph,#flow-card').count(),0);
 for(const name of ['Роли CSV','Кластеры CSV','Топ CSV']){const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:`${name} ↓`,exact:true}).click();assert.match((await downloadEvent).suggestedFilename(),/\.csv$/);}
 await page.setViewportSize({width:390,height:844});await page.selectOption('#language','kk');await page.fill('#client-search',gid);await page.locator('#title').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'clients-mobile-kk.png')});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.click('[data-section="clusters"]');await page.locator('.cluster-card').first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.selectOption('#language','en');await page.click('#theme');await page.locator('.cluster-card').first().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'signals-mobile-en.png')});
 await page.reload();await page.locator('.cluster-card').first().waitFor();assert.equal(await page.locator('#source').textContent(),'Original dataset');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('#language').inputValue(),'en');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 console.log(JSON.stringify({status:'passed',allClients:2248,roleFilter:38,gid,memoryUpload:'passed',languages:3,themes:2,downloads:3,externalRequests:0,mobileOverflow:false},null,2));
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
